INSERT INTO NPL_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL, SITUACAO) VALUES (1, 'Paulo', 'admin', '123456789','paulomend.dev@gmail.com', 'ATIVO');

ALTER SEQUENCE NPL_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO NPL_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');


ALTER SEQUENCE NPL_PERFIL_SEQ RESTART WITH 4;

INSERT INTO NPL_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');


ALTER SEQUENCE NPL_RECURSO_SEQ RESTART WITH 4;